//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolylineAlgorithm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolylineAlgorithm.Properties.ExceptionMessageResource", typeof(ExceptionMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be an empty..
        /// </summary>
        internal static string ArgumentCannotBeEmptyMessage {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Value {0} is out of range. Expected range between {1} and {2}..
        /// </summary>
        internal static string ArgumentOutOfRangeFormat {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a finite number..
        /// </summary>
        internal static string ArgumentValueMustBeFiniteNumber {
            get {
                return ResourceManager.GetString("ArgumentValueMustBeFiniteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string CoordinateValueMustBeBetweenValuesFormat {
            get {
                return ResourceManager.GetString("CoordinateValueMustBeBetweenValuesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded values couldn&apos;t be written to the buffer..
        /// </summary>
        internal static string CouldNotWriteEncodedValueToTheBufferMessage {
            get {
                return ResourceManager.GetString("CouldNotWriteEncodedValueToTheBufferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array length {0} must be greater than the polyline length {1}..
        /// </summary>
        internal static string DestinationArrayLengthMustBeEqualOrGreaterThanPolylineLengthFormat {
            get {
                return ResourceManager.GetString("DestinationArrayLengthMustBeEqualOrGreaterThanPolylineLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline does not end with a valid block terminator..
        /// </summary>
        internal static string InvalidPolylineBlockTerminatorMessage {
            get {
                return ResourceManager.GetString("InvalidPolylineBlockTerminatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline contains invalid character &apos;{0}&apos; at position {1}..
        /// </summary>
        internal static string InvalidPolylineCharacterFormat {
            get {
                return ResourceManager.GetString("InvalidPolylineCharacterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline must be at least {1} characters long, but was {0}..
        /// </summary>
        internal static string InvalidPolylineLengthFormat {
            get {
                return ResourceManager.GetString("InvalidPolylineLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block at position {0} exceeds 7 characters..
        /// </summary>
        internal static string PolylineBlockTooLongFormat {
            get {
                return ResourceManager.GetString("PolylineBlockTooLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be shorten than {1} characters. Value: {0}..
        /// </summary>
        internal static string PolylineCannotBeShorterThanFormat {
            get {
                return ResourceManager.GetString("PolylineCannotBeShorterThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline is malformed at position {0}..
        /// </summary>
        internal static string PolylineIsMalformedAtFormat {
            get {
                return ResourceManager.GetString("PolylineIsMalformedAtFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack alloc limit must be equal or greater than {0}..
        /// </summary>
        internal static string StackAllocLimitMustBeEqualOrGreaterThanFormat {
            get {
                return ResourceManager.GetString("StackAllocLimitMustBeEqualOrGreaterThanFormat", resourceCulture);
            }
        }
    }
}
