//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolylineAlgorithm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolylineAlgorithm.Properties.ExceptionMessageResource", typeof(ExceptionMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be CoordinateValueType.{0}..
        /// </summary>
        internal static string ArgumentCannotBeCoordinateValueTypeMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentCannotBeCoordinateValueTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be an empty enumeration..
        /// </summary>
        internal static string ArgumentCannotBeEmptyEnumerationMessage {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyEnumerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range for the specified type {0}..
        /// </summary>
        internal static string ArgumentOutOfRangeForSpecifiedCoordinateValueTypeMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeForSpecifiedCoordinateValueTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a finite number..
        /// </summary>
        internal static string ArgumentValueMustBeFiniteNumber {
            get {
                return ResourceManager.GetString("ArgumentValueMustBeFiniteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size must be greater than {0}..
        /// </summary>
        internal static string BufferSizeMustBeGreaterThanMessageFormat {
            get {
                return ResourceManager.GetString("BufferSizeMustBeGreaterThanMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string CoordinateValueMustBeBetweenValuesMessageFormat {
            get {
                return ResourceManager.GetString("CoordinateValueMustBeBetweenValuesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded values couldn&apos;t be written to the buffer. Please, report a bug on GitHub with reproducible sample. Thank you, Pete..
        /// </summary>
        internal static string CouldNotWriteEncodedValueToTheBuffer {
            get {
                return ResourceManager.GetString("CouldNotWriteEncodedValueToTheBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array length must be greater than the polyline length..
        /// </summary>
        internal static string DestinationArrayLengthMustBeEqualOrGreaterThanPolylineLengthMessage {
            get {
                return ResourceManager.GetString("DestinationArrayLengthMustBeEqualOrGreaterThanPolylineLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be shorten than {1} characters. Actual length: {0}..
        /// </summary>
        internal static string PolylineCannotBeShorterThanExceptionMessage {
            get {
                return ResourceManager.GetString("PolylineCannotBeShorterThanExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline is malformed at position {0}..
        /// </summary>
        internal static string PolylineStringIsMalformedMessage {
            get {
                return ResourceManager.GetString("PolylineStringIsMalformedMessage", resourceCulture);
            }
        }
    }
}
