name: 'Create GitHub release'
author: 'Pete Sramek'
description: 'Create GitHub release.'
inputs:
    branch-name:
      description: 'The name of the branch to extract version from.'
      required: true

runs:
  using: composite
  steps:
    - name: 'Checkout ${{ github.head_ref || github.ref }}'
      uses: actions/checkout@v5
    - name: 'Extract version from branch name'
      id: extract-version
      uses: './.github/actions/versioning/extract-version'
      with:
        branch-name: ${{ inputs.branch-name }}
    - name: 'Create GitHub release PolylineAlgorithm ${{ steps.extract-version.outputs.package-version }}"'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ steps.extract-version.outputs.package-version }} --generate-notes --discussion-category "GeneralDiscussions"
