name: 'Build with .NET CLI'
author: 'Pete Sramek'
description: 'Compiles source code, uploads build artifacts.'
inputs:
  # Required
  working-directory:
    description: 'The working directory where the changes will be pushed from.'
    required: true
  target-branch:
    description: 'The branch to push changes to.'
    required: true
  commit-message:
    description: 'The commit message to use when pushing changes.'
    required: true

runs:  
  using: "composite"
  steps:    
    - name: Add changes from ${{ inputs.working-directory }}
      shell: bash
      run: |
        git fetch origin
        git checkout -b ${{ inputs.target-branch }} origin/${{ inputs.target-branch }}
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add -- .
    - name: Check for changes in ${{ inputs.working-directory }}
      shell: bash
      run: |
        git diff --staged --quiet -- .
      continue-on-error: true
      id: check-diff
    - name: Push changes to ${{ inputs.target-branch }}, if exists
      if: ${{ steps.check-diff.outcome == 'success' }}
      shell: bash
      run: |
        echo "No changes to commit in ${{ inputs.working-directory }}"
    - name: Push changes to ${{ inputs.target-branch }}, if exists
      if: ${{ steps.check-diff.outcome == 'failure' }}
      shell: bash
      run: |
        git commit -m'${{ inputs.commit-message }}' -- ${{ inputs.working-directory }}
        git push