name: 'Push Changes'
author: 'Pete Sramek'
description: 'Push changes to a specified branch in the repository.'
inputs:
  # Required
  artifact-name:
    description: 'Name of the artifact to download before pushing changes.'
    required: true
  working-directory:
    description: 'The working directory where the changes will be pushed from.'
    required: true
  target-branch:
    description: 'The branch to push changes to.'
    required: true
  commit-message:
    description: 'The commit message to use when pushing changes.'
    required: true
# Optional
  dotnet_sdk_version:
    description: '.NET SDK version. Default: 9.x'
    required: false
    default: '9.x'

runs:  
  using: "composite"
  steps:
    - name: 'Checkout ${{ github.head_ref || github.ref }}'
      uses: actions/checkout@v4
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-sdk-version }}
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}
    - name: Add changes from ${{ inputs.working-directory }}
      shell: bash
      run: |
        ls -R ${{ inputs.working-directory }}
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add --  ${{ inputs.working-directory }}
    - name: Check for changes in ${{ inputs.working-directory }}
      shell: bash
      run: |
        git diff origin/${{ inputs.target-branch }} --staged --quiet -- ${{ inputs.working-directory }}
      continue-on-error: true
      id: check-diff
    - name: Push changes to ${{ inputs.target-branch }}, if exists
      if: ${{ steps.check-diff.outcome == 'success' }}
      shell: bash
      run: |
        echo "No changes to commit in ${{ inputs.working-directory }}"
    - name: Push changes to ${{ inputs.target-branch }}, if exists
      if: ${{ steps.check-diff.outcome == 'failure' }}
      shell: bash
      run: |
        git stash push -- ${{ inputs.working-directory }}
        git fetch origin
        git checkout -b ${{ inputs.target-branch }} origin/${{ inputs.target-branch }} --force
        git stash pop
        git commit -m'${{ inputs.commit-message }}' -- ${{ inputs.working-directory }}
        git push
        git checkout ${{ github.head_ref || github.ref }}