name: 'Generate docs with docfx'
author: 'Pete Sramek'
description: 'Generate documentation using docfx'
inputs:
# Required
  docfx-json-manifest:
    description: 'Path to the docfx JSON manifest file'
    required: true
  staging-directory:
    description: 'Staging directory for generated documentation'
    required: true
  target-directory:
    description: 'Target directory for generated documentation'
    required: true
# Optional
  dotnet_sdk_version:
    description: '.NET SDK version. Default: 9.x'
    required: false
    default: '9.x'

runs:
  using: composite
  steps:
    - name: 'Checkout ${{ github.head_ref || github.ref }}'
      uses: actions/checkout@v4
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-sdk-version }}
    - name: 'Update docfx tool'
      run: dotnet tool update -g docfx
      shell: bash
    - name: 'Generate documentation'
      run: docfx ${{ inputs.docfx-json-manifest }}
      shell: bash
    - name: 'Create target directory'
      run: mkdir -p ${{ inputs.target-directory }}
      shell: bash
    - name: 'Move files from staging to target directory'
      run: mv ${{ inputs.staging-directory }} ${{ inputs.target-directory }}
      shell: bash