blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/petesramek/polyline-algorithm-csharp/discussions
    about: Use GitHub Discussions for questions, ideas, or general feedback.
