name: 'Generate markdown with Liquid Test Reports CLI'
author: 'Pete Sramek'
description: 'Run tests, collects code coverage, logs test results, uploads test artifacts'
inputs:
# Required
  test-result-folder:
    description: 'Folder where test results are stored'
    required: true
# Optional
  dotnet_sdk_version:
    description: '.NET SDK version. Default: 9.x'
    required: false
    default: '9.x'
  test-report-filename:
    description: 'Filename of the test report. Default: test-report.md'
    required: false
    default: 'test-report.md'
  write-step-summary:
    description: 'Write test summary to step summary. Default: true'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: 'Checkout ${{ github.head_ref || github.ref }}'
      uses: actions/checkout@v4
    
    - name: 'Setup .NET ${{ inputs.dotnet_sdk_version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_sdk_version }}

    - name: Install LiquidTestReports.Cli
      shell: bash
      run: dotnet tool install --global LiquidTestReports.Cli --prerelease
  
    - name: Generate test report
      shell: bash
      env:
        test-report-file: ${{ endsWith($(inputs.test-result-folder), '/') && ${inputs.test-result-folder)$(inputs.test-report-filename) || $(inputs.test-result-folder)/$(inputs.test-report-filename) }}
      run: liquid --inputs "Folder=${{ env.test-result-folder }};File=**/*.trx;Format=Trx" --output-file ${{ env.test-report-file }}
    
    - name: Write summary
      if: ${{ inputs.write-step-summary == 'true' }}
      shell: bash
      env:
        test-report-file: ${{ endsWith($(inputs.test-result-folder), '/') && ${inputs.test-result-folder)$(inputs.test-report-filename) || $(inputs.test-result-folder)/$(inputs.test-report-filename) }}
      run: cat ${{ env.test-report-file }} >> $GITHUB_STEP_SUMMARY