name: 'Determine version'
author: 'Pete Sramek'
description: 'Determines versions for the build.'
inputs:
# Required
  branch-name:
    description: 'Branch name.'
    required: true
# Optional
  version-format:
    description: 'Version format. Default: ''(<Major>?/d+).(<Minor>?/d+)'''
    required: false
    default: '(\d+).(\d+)'
  dotnet_sdk_version:
    description: '.NET SDK version. Default: ''9.x'''
    required: false
    default: '9.x'
    
runs:  
  using: "composite"
  steps:
    - name: 'Checkout ${{ github.head_ref || github.ref }}'
      uses: actions/checkout@v5
    
    - name: 'Setup .NET ${{ inputs.dotnet_sdk_version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_sdk_version }}

    - name: 'Capture version in branch name'
      shell: bash
      run: |
        echo "${{ inputs.branch-name }}"
        echo "${{ inputs.version-format }}"
        echo "$(${{ inputs.branch-name }} | grep -Po '${{ inputs.version-format }}')"
