name: Apply file header

on:
  push:
    branches:
    - 'develop/**'
  pull_request:
    branches:
    - 'main'
    - 'preview/**'
    - 'release/**'
    - 'support/**'
    paths:
      - '**.cs'

permissions:
  contents: write

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:      
  versioning:
    name: Format file headers with .NET ${{ vars.DOTNET_SDK_VERSION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET ${{ vars.DOTNET_SDK_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}
    - run: dotnet format --diagnostics IDE0073 --verbosity diagnostics
      name: Apply file header rule
    - run: git add .
      name: Stage file header rule changes
    - run: git commit -m "applied file header rule"
      name: Commit file header rule changes
    - run: git push origin ${{ github.ref }}
      name: Push file header rule changes to ${{ github.ref }}
