name: Apply file header

on:
  pull_request:
    branches:
    - 'main'
    - 'preview/**'
    - 'release/**'
    - 'support/**'
    paths-ignore:
    - '!src/**'
  merge_group:
    types: [checks_requested]

permissions:
  contents: write

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:      
  versioning:
    name: Versioning with GitVersion ${{ vars.GIT_VERSION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: dotnet format --diagnostics IDE0073
      name: Apply file header rule
      working-directory: src
    - run: dotnet format --diagnostics IDE0073
      name: Apply file header rule
      working-directory: src
    - run: git add .
      name: Apply file header rule
      working-directory: src
    - run: git commit -m "applied file header rule"
      name: Commit file header rule changes
      working-directory: src
    - run: git push origin ${{ github.ref }}
      name: Push to ${{ github.ref }}
      working-directory: src
