name: 'Create release'

on:
  pull_request_target:
    branches:
      - 'preview/**'
      - 'release/**'
    paths:
      - 'src/**'

permissions:
  actions: read
  pages: write
  id-token: write
  contents: write

concurrency: 
  group: create-release-${{ github.head_ref || github.ref }}      
  cancel-in-progress: false

env:
  dotnet-sdk-version: '9.x'
  build-configuration: 'Release'
  build-platform: 'Any CPU'
  git-version: '6.0.x'
  test-result-directory: 'test-results'
  nuget-packages-directory: 'nuget-packages'
