name: 'Determine version'

on:
  workflow_call:
    inputs:
    # Required
      config-file-path:
        description: 'Path to the configuration file.'
        type: string
        required: true
      run-number:
        description: 'The run number of the parent workflow.'
        type: string
        required: true
    # Optional
      dotnet-sdk-version:
        description: 'Version of the .NET SDK to use. Default: ''9.0.x''.'
        type: string
        required: false
        default: '9.0.x'
      gitversion-version:
        description: 'Version of GitVersion to use. Default: ''6.0.x''.'
        required: false
        type: string
        default: '6.0.x'
      prerelease-tag:
        description: 'The prerelease tag to use. Default: ''''.'
        type: string
        required: false
        default: ''
    outputs:
      assembly-version:
        description: "The assembly version."
        value: ${{ jobs.version.outputs.assembly-version }}
      assembly-informational-version:
        description: "The assembly informational version."
        value: ${{ jobs.version.outputs.assembly-informational-version }}
      file-version:
        decsription: "The file version."
        value: ${{ jobs.version.outputs.file-version }}
      package-version:
        description: "The package version."
        value: ${{ jobs.version.outputs.package-version }}

jobs:
  version:
    name: 'Version'
    runs-on: ubuntu-latest

    outputs:
      assembly-version: ${{ env.assembly-version }}
      assembly-informational-version: ${{ env.assembly-informational-version }}
      file-version: ${{ env.file-version }}
      package-version: ${{ env.package-version }}

    steps:

      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup GitVersion ${{ env.git-version }}'
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: ${{ inputs.gitversion-version }}
          preferLatestVersion: true

      - name: 'Determine version'
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true
          configFilePath: ${{ inputs.config-file-path }}

      - name: 'Set assembky version'
        shell: bash
        run: echo "assembly-version=${{ steps.gitversion.outputs.AssemblySemFileVer }}.${{ inputs.run-number }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" >> $GITHUB_ENV

      - name: 'Set assembky informational version'
        shell: bash
        run: echo "assembly-informational-version=${{ steps.gitversion.outputs.assemblySemVer }}.${{ inputs.run-number }}+${{ steps.gitversion.outputs.sha }}" >> $GITHUB_ENV

      - name: 'Set file version'
        shell: bash
        run: echo "file-version=${{ steps.gitversion.outputs.AssemblySemFileVer }}.${{ inputs.run-number }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" >> $GITHUB_ENV

      - if: ${{ inputs.prerelease-tag == '' }}
        name: 'Set package version'
        shell: bash
        run: echo "package-version=${{ steps.gitversion.outputs.AssemblySemVer }}.${{ inputs.run-number }}" >> $GITHUB_ENV

      - if: ${{ inputs.prerelease-tag != '' && startsWith('-', inputs.prerelease-tag) }}
        name: 'Set package version'
        shell: bash
        run: echo "package-version=${{ steps.gitversion.outputs.AssemblySemVer }}.${{ inputs.run-number }}${{ inputs.prerelease-tag}}" >> $GITHUB_ENV

      - if: ${{ inputs.prerelease-tag != '' && !startsWith('-', inputs.prerelease-tag) }}
        name: 'Set package version'
        shell: bash
        run: echo "package-version=${{ steps.gitversion.outputs.AssemblySemVer }}.${{ inputs.run-number }}-${{ inputs.prerelease-tag}}" >> $GITHUB_ENV
          