name: 'Determine version'

on:
  workflow_call:
    inputs:
    # Required
      config-file-path:
        description: 'Path to the configuration file.'
        type: string
        required: true
      prerelease:
        description: 'Indicates whether the version should be a pre-release version.'
        type: boolean
        required: true
      run-number:
        description: 'The run number of the parent workflow.'
        type: number
        required: true
    # Optional
      dotnet-sdk-version:
        description: 'Version of the .NET SDK to use. Default: ''9.0.x''.'
        type: string
        required: false
        default: '9.0.x'
      gitversion-version:
        description: 'Version of GitVersion to use. Default: ''6.0.x''.'
        required: true
        type: string
        default: '6.0.x'

jobs:
  version:
    name: 'Version'
    runs-on: ubuntu-latest

    outputs:
      assembly-version: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ inputs.run-number }}
      assembly-informational-version: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}+${{ steps.gitversion.outputs.sha }}
      file-version: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}
      package-version: ${{ fromJSON(format('[ "{0}{1}", "{0}" ]', steps.gitversion.outputs.assemblySemVer, steps.gitversion.outputs.preReleaseLabelWithDash))[fromJSON(inputs.prerelease)] }}

    steps:

      - if: ${{ !(inputs.nuget-feed-server == 'NuGet' || inputs.nuget-feed-server == 'AzureArtifacts') }}
        name: 'Invalid NuGet feed server type'
        shell: bash
        run: |
          echo 'Invalid NuGet feed server type ${{ inputs.nuget-feed-server }}. Allowed values are 'NuGet' or 'AzureArtifacts'.'
          exit 1

      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup GitVersion ${{ env.git-version }}'
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: ${{ inputs.gitversion-version }}
          preferLatestVersion: true

      - name: 'Determine version'
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true
          configFilePath: ${{ inputs.config-file-path }}
          