name: .NET

on:
  push:
    branches:
    - 'preview/**'
    - 'release/**'
    paths-ignore:
    - '!src/**'
  pull_request:
    branches:
    - 'main'
    - 'preview/**'
    - 'release/**'
    - 'support/**'
    paths-ignore:
    - '!src/**'

permissions:
  actions: read
  pages: write
  id-token: write

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  is_release: ${{ startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'preview') }}
  is_preview: ${{ startsWith(github.ref_name, 'preview') }}

jobs:      
  versioning:
    name: Versioning with GitVersion ${{ vars.GIT_VERSION }}
    runs-on: ubuntu-latest
    outputs:
      ASSEMBLY_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}
      ASSEMBLY_INFORMATIONAL_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}+${{ steps.gitversion.outputs.sha }}
      FILE_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}
      PACKAGE_VERSION: ${{ fromJSON(format('[ "{0}{1}", "{0}" ]', steps.gitversion.outputs.assemblySemVer, steps.gitversion.outputs.preReleaseLabelWithDash))[fromJSON(env.is_release)] }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion ${{ vars.GIT_VERSION }}
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: ${{ vars.GIT_VERSION }}
        preferLatestVersion: true
    - name: Calculate version with GitVersion ${{ vars.GIT_VERSION }}
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        useConfigFile: true
        configFilePath: ./.gitversion/version.yml

  build:
    name: Build with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [versioning]
    runs-on: ubuntu-latest
    env:
      ASSEMBLY_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_VERSION }}
      ASSEMBLY_INFORMATIONAL_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_INFORMATIONAL_VERSION }}
      FILE_VERSION: ${{ needs.versioning.outputs.FILE_VERSION }}
      PACKAGE_VERSION: ${{ needs.versioning.outputs.PACKAGE_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET ${{ vars.DOTNET_SDK_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}
    - name: Build with .NET ${{ vars.DOTNET_SDK_VERSION }}
      run: dotnet build ${{ vars.SRC_SEARCH_PATTERN }} --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} /p:Version=${{ env.ASSEMBLY_VERSION }} /p:AssemblyInformationalVersion=${{ env.ASSEMBLY_INFORMATIONAL_VERSION }} /p:FileVersion=${{ env.FILE_VERSION }}
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          **/bin/*
          **/obj/*

  test:
    name: Test with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ vars.DOTNET_SDK_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}
    - name: Test with .NET ${{ vars.DOTNET_SDK_VERSION }}
      run: dotnet test ${{ vars.TEST_SEARCH_PATTERN }} --configuration ${{ vars.BUILD_CONFIGURATION }} --verbosity normal --settings unit-test.runsettings -- --coverage --coverage-output-format cobertura --report-trx --results-directory ${{ runner.temp }}/test-results/
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ${{ runner.temp }}/test-results/*
    - run: dotnet tool install --global LiquidTestReports.Cli --prerelease
    - run: ls -R ${{ runner.temp }}/test-results/
    - run: liquid --inputs "Folder=${{ runner.temp }}/test-results/;File=**/*.trx;Format=Trx" --output-file ${{ runner.temp }}/test-results/test-report.md
    - run: cat ${{ runner.temp }}/test-results/*.md >> $GITHUB_STEP_SUMMARY
      name: Write Test Results Summary
    - run: dotnet tool update --global dotnet-coverage
      name: Update dotnet-coverage tool
    - run: dotnet-coverage merge --output ${{ runner.temp }}/test-results/test-result.cobertura.xml --output-format cobertura "${{ runner.temp }}/test-results/**/*.cobertura.xml"
      name: Merge Code Coverage Results
    - run: dotnet tool update --global dotnet-reportgenerator-globaltool
      name: Update dotnet-reportgenerator-globaltool tool
    - run: reportgenerator -reports:${{ runner.temp }}/test-results/test-result.cobertura.xml -targetdir:${{ runner.temp }}/test-results/coverage-report -reporttypes:"MarkdownSummary"
      name: Generate Code Coverage Results
    - run: cat ${{ runner.temp }}/test-results/coverage-report/Summary.md >> $GITHUB_STEP_SUMMARY
      name: Write Code Coverage Summary

  pack:
    name: Pack with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [build, versioning]
    runs-on: ubuntu-latest
    env:
      ASSEMBLY_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_VERSION }}
      ASSEMBLY_INFORMATIONAL_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_INFORMATIONAL_VERSION }}
      FILE_VERSION: ${{ needs.versioning.outputs.FILE_VERSION }}
      PACKAGE_VERSION: ${{ needs.versioning.outputs.PACKAGE_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET ${{ vars.DOTNET_SDK_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Pack with .NET ${{ vars.DOTNET_SDK_VERSION }}
      run: dotnet pack ${{ vars.SRC_SEARCH_PATTERN }} --no-build --no-restore --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} /p:PackageVersion=${{ env.PACKAGE_VERSION }} /p:Version=${{ env.ASSEMBLY_VERSION }} /p:AssemblyInformationalVersion=${{ env.ASSEMBLY_INFORMATIONAL_VERSION }} /p:FileVersion=${{ env.FILE_VERSION }} --output ${{ runner.temp }}/packages/
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          ${{ runner.temp }}/packages/**/*.nupkg
          ${{ runner.temp }}/packages/**/*.snupkg

  benchmark:
    if: ${{ github.env.is_release || vars.BENCHMARKDOTNET_RUN_OVERRIDE == 'true' }}
    name: Benchmark with .NET ${{ vars.DOTNET_SDK_VERSION }} on ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
         6.x
         8.x
         9.x
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Benchmark
      working-directory: ${{ vars.BENCHMARKDOTNET_WORKING_DIRECTORY }}
      run: dotnet run --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} --framework ${{ vars.BUILD_FRAMEWORK }} --runtimes ${{ vars.BENCHMARKDOTNET_RUNTIMES }} --filter ${{ vars.BENCHMARKDOTNET_FILTER }} --exporters GitHub --memory --artifacts ${{ runner.temp }}/benchmarks/ --join
    - name: Upload Benchmark Results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-${{ matrix.os }}
        path: |
          ${{ runner.temp }}/benchmarks/**/*-report-github.md
    - name: Write Benchmark Summary 
      shell: bash
      run: cat **/*-report-github.md > $GITHUB_STEP_SUMMARY
      working-directory: ${{ runner.temp }}/benchmarks/

  publish-docs:
    if: ${{ github.env.is_release && !github.env.is_preview }}
    name: Docs with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [benchmark,test]  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}

    - name: Download Benchmarks
      uses: actions/download-artifact@v4
      with:
        pattern: benchmark-*
        path: ${{ runner.temp }}/benchmarks/
        merge-multiple: false

    - run: |
        echo -e '\n## Windows' >> ${{ github.workspace}}/docfx/benchmarks/index.md
        cat benchmark-windows-latest/**/*.md >> ${{ github.workspace}}/docfx/benchmarks/index.md
        echo -e '\n## Linux' >> ${{ github.workspace}}/docfx/benchmarks/index.md
        cat benchmark-ubuntu-latest/**/*.md >> ${{ github.workspace}}/docfx/benchmarks/index.md
        echo -e '\n## macOS' >> ${{ github.workspace}}/docfx/benchmarks/index.md
        cat benchmark-macos-latest/**/*.md >> ${{ github.workspace}}/docfx/benchmarks/index.md
      working-directory: ${{ runner.temp }}/benchmarks/
  
    - run: dotnet tool update -g docfx
    - run: docfx ./docfx/docfx.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  publish-package-internal:
    if: ${{ !github.env.is_release }}
    name: Publish package with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [pack]  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}

    - name: Download Benchmarks
      uses: actions/download-artifact@v4
      with:
        name: package
        path: ${{ runner.temp }}/packages/

    - run: |
        dotnet nuget add source ${{ secrets.PRIVATE_NUGET_PACKAGE_FEED }} --name private-feed --username irrelevant --password ${{ secrets.PRIVATE_NUGET_PACKAGE_FEED_API_KEY }} --store-password-in-clear-text
        dotnet nuget push **/*.nupkg --source private-feed --api-key ${{ secrets.PRIVATE_NUGET_PACKAGE_FEED_API_KEY }}
      working-directory: ${{ runner.temp }}/packages/
  
  release-package:
    if: ${{ github.env.is_release }}
    name: Release package with .NET ${{ vars.DOTNET_SDK_VERSION }}
    needs: [pack, test]  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_SDK_VERSION }}

    - name: Download Benchmarks
      uses: actions/download-artifact@v4
      with:
        name: package
        path: ${{ runner.temp }}/packages/

    - run: |
        dotnet nuget push **/*.nupkg --source ${{ vars.PUBLIC_NUGET_PACKAGE_FEED }} --api-key ${{ secrets.PUBLIC_NUGET_PACKAGE_FEED_API_KEY }}
      working-directory: ${{ runner.temp }}/packages/