# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build with .NET 9

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          **/bin/*
          **/obj/*

  test:
    name: Test with MsTest
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
    - uses: actions/download-artifact@v4
      with:
        name: build
        path: .
        merge-multiple: true
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --verbosity normal

  benchmark:
    name: Benchmark with .NET ${{ matrix.netversion }}.0 on ${{ matrix.os }}
    needs: [build]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        netversion: [7, 8, 9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.netversion }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.netversion }}.x
    - name: Fix libssl
      if: ${{ matrix.netversion == 5 && matrix.os == 'ubuntu-latest' }}
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
    - uses: actions/download-artifact@v4
      with:
        name: build
        path: .
        merge-multiple: true
    - name: Benchmark
      working-directory: ./benchmarks/PolylineAlgorithm.Benchmarks
      run: dotnet run --configuration Release --framework net${{ matrix.netversion }}.0