name: .NET

on:
  push:
    branches:
    - 'preview/**'
    - 'release/**'
  pull_request:
    branches:
    - 'main'
    - 'preview/**'
    - 'release/**'
    - 'support/**'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  is_release: ${{ startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'preview') }}
  is_preview: ${{ startsWith(github.ref_name, 'preview') }}

jobs:      
  versioning:
    name: Versioning with GitVersion ${{ vars.GIT_VERSION }}
    runs-on: ubuntu-latest
    outputs:
      ASSEMBLY_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}
      ASSEMBLY_INFORMATIONAL_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}+${{ steps.gitversion.outputs.sha }}
      FILE_VERSION: ${{ steps.gitversion.outputs.assemblySemVer }}.${{ github.run_number }}
      PACKAGE_VERSION: ${{ fromJSON(format('[ "{0}.{1}.{2}", "{0}.{2}" ]', steps.gitversion.outputs.assemblySemVer, steps.gitversion.outputs.preReleaseLabelWithDash, github.run_number))[fromJSON(env.is_release)] }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: 'echo ${{ github.ref_name }}'
    - name: Install GitVersion ${{ vars.GIT_VERSION }}
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: ${{ vars.GIT_VERSION }}
        preferLatestVersion: true
    - name: Calculate version with GitVersion ${{ vars.GIT_VERSION }}
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        useConfigFile: true
        configFilePath: ./.gitversion/version.yml

  build:
    name: Build with .NET ${{ vars.DOTNET_VERSION }}
    needs: [versioning]
    runs-on: ubuntu-latest
    env:
      ASSEMBLY_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_VERSION }}
      ASSEMBLY_INFORMATIONAL_VERSION: ${{ needs.versioning.outputs.ASSEMBLY_INFORMATIONAL_VERSION }}
      FILE_VERSION: ${{ needs.versioning.outputs.FILE_VERSION }}
      PACKAGE_VERSION: ${{ needs.versioning.outputs.PACKAGE_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET ${{ vars.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}
    - name: Build with .NET ${{ vars.DOTNET_VERSION }}
      run: dotnet build ./src/**/*.csproj --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} -p:Version=${{ env.ASSEMBLY_VERSION }} -p:AssemblyInformationalVersion=${{ env.ASSEMBLY_INFORMATIONAL_VERSION }} -p:FileVersion=${{ env.FILE_VERSION }}
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          **/bin/*
          **/obj/*

  test:
    name: Test with .NET ${{ vars.DOTNET_VERSION }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ vars.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}
    - name: Test with .NET ${{ vars.DOTNET_VERSION }}
      run: dotnet test ./tests/**/*Tests.csproj --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} --verbosity normal --settings unit-test.runsettings --logger trx --collect:"Code Coverage" --results-directory test-results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/test-results/*

  pack:
    name: Pack with .NET ${{ vars.DOTNET_VERSION }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET ${{ vars.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Pack with .NET ${{ vars.DOTNET_VERSION }}
      run: dotnet pack ./src/**/*.csproj --no-build --no-restore --configuration ${{ vars.BUILD_CONFIGURATION }}  /p:Platform=${{ vars.BUILD_PLATFORM }}
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          **/*.nupkg

  benchmark:
    if: ${{ github.env.is_release }}
    name: Benchmark on ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Benchmark
      working-directory: ./benchmarks/PolylineAlgorithm.Benchmarks
      run: dotnet run --configuration ${{ vars.BUILD_CONFIGURATION }} /p:Platform=${{ vars.BUILD_PLATFORM }} --framework ${{ vars.BUILD_FRAMEWORK }} --runtimes ${{ vars.BENCHMARKDOTNET_RUNTIMES }} --filter ${{ vars.BENCHMARKDOTNET_FILTER }}