name: 'Promote branch'

on:
  workflow_dispatch:
   inputs:
     promotion-type:
       type: choice
       options:
         - 'preview'
         - 'release'
       description: 'Promotion type.'
       required: true

permissions:
  actions: read
  id-token: write
  contents: write

concurrency:
    group: 'promote-branch-${{ inputs.promotion-type }}-${{github.ref_name }}'
    cancel-in-progress: false

env:
  dotnet-sdk-version: '9.x'
  is-development-branch: ${{ startsWith(github.ref_name, 'develop') }}
  is-maintenance-branch: ${{ startsWith(github.ref_name, 'support') }}

jobs:
  versioning:
    name: 'Extract version (new)'
    runs-on: ubuntu-latest
    outputs:
        friendly-version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Setup .NET ${{ env.dotnet-sdk-version }}'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-sdk-version }}
      - name: 'Extract version from branch name'
        id: extract-version
        uses: './.github/actions/extract-version'
        with:
          branch-name: ${{ github.ref_name }}
  workflow-variables:
    name: 'Set workflow variables'
    needs: [versioning]
    runs-on: ubuntu-latest
    outputs:
        default-branch: ${{ steps.set-default-branch.outputs.default-branch }}
        target-branch: ${{ steps.set-target-branch.outputs.target-branch }}
        target-branch-exists: ${{ steps.check-target-branch-exists.outputs.target-branch-exists }}
    steps:
      - name: 'Set target branch'
        id: set-target-branch
        run: |
          if [[ "${{ inputs.promotion-type }}" == "preview" ]]; then
            target_branch="preview/${{ needs.versioning.outputs.friendly-version }}"
          elif [[ "${{ inputs.promotion-type }}" == "release" ]]; then
            target_branch="release/${{ needs.versioning.outputs.friendly-version }}"
          fi
          
          echo "Setting target branch $target_branch."

          echo "target-branch=$target_branch" >> $GITHUB_OUTPUT
      - name: 'Get default branch'
        id: set-default-branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          default_branch=$(gh api repos/${{ github.repository }} --jq '.default_branch')
          
          echo "Setting default branch $default_branch."
          
          echo "default-branch=$default_branch" >> $GITHUB_OUTPUT
      - name: 'Check if target branch exists'
        id: check-target-branch-exists
        env:
          target-branch: ${{ needs.workflow-variables.outputs.target-branch }}
        run: |
          set +e

          git ls-remote --exit-code --heads origin ${{ env.target-branch }}

          if [[ $? -eq 0 ]]; then
            echo "Target ${{ env.target-branch }} branch does exist."
            target_branch_exists="true"
          else
            echo "Target branch ${{ env.target-branch }} does not exist."
            target_branch_exists="false"
          fi

          echo "target-branch-exists=$target_branch_exists" >> $GITHUB_OUTPUT

          set -e

  validate-promotion:
    name: 'Validate promotion'
    needs: [ versioning, workflow-variables ]
    runs-on: ubuntu-latest
    env:
      promotion-type: ${{ inputs.promotion-type }}
      default-branch: ${{ needs.workflow-variables.outputs.default-branch }}
      current-branch: ${{ github.ref_name }}
      target-branch: ${{ needs.workflow-variables.outputs.target-branch }}
    outputs:
        target-branch: ${{ steps.compose-target-branch.outputs.target-branch }}
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Check promotion type'
        if: ${{ (env.promotion-type != 'release') && (env.promotion-type != 'preview') }}
        run: |
          echo "Invalid promotion type ${{ inputs.promotion-type }}"
          exit 1
      - name: 'Validate current branch'
        if: ${{ (env.isdevelopment-branch == 'false') && (env.is-maintenance-branch == 'false') }}
        run: |
          echo "Invalid current branch '${{ github.ref_name }}'"
          exit 1
      - name: 'Validate default and current branch'
        if: ${{ env.default-branch == env.current-branch }}
        run: |
          echo "Default and current branch cannot be the same."
          echo "Default branch is '${{ env.default-branch }}'"
          echo "Current branch is '${{ env.current-branch }}'"
          exit 1

  promote-branch:
    name: 'Promote branch ${{ github.ref_name }} to ${{ needs.workflow-variables.outputs.target-branch }}'
    needs: [ workflow-variables, validate-promotion ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Setup .NET ${{ env.dotnet-sdk-version }}'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-sdk-version }}
      - name: 'Create target branch'
        if: ${{ needs.workflow-variables.outputs.target-branch-exists == 'false' }}
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git fetch origin
          git switch ${{ needs.workflow-variables.outputs.default-branch }}
          git checkout -b ${{ needs.workflow-variables.outputs.target-branch }}
          git push
