name: 'Promote branch'

on:
  workflow_dispatch:
   inputs:
     promotion-type:
       type: choice
       options:
         - 'preview'
         - 'release'
       description: 'Promotion type.'
       required: true

permissions:
  actions: read
  id-token: write
  contents: write

concurrency:
    group: 'promote-branch-${{ inputs.promotion-type }}-${{github.ref_name }}'
    cancel-in-progress: false

env:
  dotnet-sdk-version: '9.x'
  is-development-branch: ${{ startsWith(github.ref_name, 'develop') }}
  is-maintenance-branch: ${{ startsWith(github.ref_name, 'support') }}

jobs:
  versioning:
    name: 'Extract version (new)'
    runs-on: ubuntu-latest
    outputs:
        friendly-version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Setup .NET ${{ env.dotnet-sdk-version }}'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-sdk-version }}
      - name: 'Extract version from branch name'
        id: extract-version
        uses: './.github/actions/extract-version'
        with:
          branch-name: ${{ github.ref_name }}
  workflow-variables:
    name: 'Set workflow variables'
    needs: [versioning]
    runs-on: ubuntu-latest
    outputs:
        target-branch: ${{ steps.compose-target-branch.outputs.target-branch }}
        target-branch-exists: ${{ steps.validate-target-branch.outputs.target-branch-exists }}
    steps:
      - name: 'Compose target branch name'
        id: compose-target-branch
        run: |
          if [[ "${{ inputs.promotion-type }}" == "preview" ]]; then
            target_branch="preview/${{ needs.versioning.outputs.friendly-version }}"
          elif [[ "${{ inputs.promotion-type }}" == "release" ]]; then
            target_branch="release/${{ needs.versioning.outputs.friendly-version }}"
          fi
          
          echo "Target branch name: $target_branch"

          echo "target-branch=$target_branch" >> $GITHUB_OUTPUT
#       - name: 'Get default branch'
# -       id: get-default-branch
#         run: |
#           set +e
#           default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
#           echo "default-branch=$default_branch" >> $GITHUB_OUTPUT
#           set -e
      - name: 'Get default branch'
        id: get-default-branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo $(gh api repos/${{ github.repository }} --jq '.default_branch')
      - name: 'Validate target branch in origin'
        id: validate-target-branch
        env:
          target-branch: ${{ needs.workflow-variables.outputs.target-branch }}
        run: |
          set +e

          git ls-remote --exit-code --heads origin ${{ env.target-branch }}

          if [[ $? -eq 0 ]]; then
            echo "Target branch exist: ${{ env.target-branch }}"
            target_branch_exists="true"
          else
            echo "Target branch does not exist: ${{ env.target-branch }}"
            target_branch_exists="false"
          fi

          echo "target-branch-exists=$target_branch_exists" >> $GITHUB_OUTPUT

          set -e

  validate-promotion:
    name: 'Validate promotion'
    needs: [ versioning, workflow-variables ]
    runs-on: ubuntu-latest
    outputs:
        target-branch: ${{ steps.compose-target-branch.outputs.target-branch }}
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Check promotion type'
        if: ${{ (inputs.promotion-type != 'release') && (inputs.promotion-type != 'preview') }}
        run: |
          echo "Invalid promotion type: ${{ inputs.promotion-type }}"
          exit 1
      - name: 'Validate source branch'
        if: ${{ (env.isdevelopment-branch == 'false') && (env.is-maintenance-branch == 'false') }}
        run: |
          echo "Invalid source branch: ${{ github.ref_name }}"
          exit 1

  promote-branch:
    name: 'Promote branch ${{ github.ref_name }} to ${{ needs.workflow-variables.outputs.target-branch }}'
    needs: [ workflow-variables, validate-promotion ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v5
      - name: 'Setup .NET ${{ env.dotnet-sdk-version }}'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-sdk-version }}
      - name: 'Create target branch'
        if: ${{ needs.workflow-variables.outputs.target-branch-exists == 'false' }}
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git fetch origin
          git checkout -b ${{ needs.workflow-variables.outputs.target-branch }} origin/HEAD
          git push
