name: 'Publish Documentation'

on:
  workflow_dispatch:
  push:
    branches:
      - 'docs'
    paths:
      - 'docs/**'

jobs:
  release-package:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    env:
      working-directory: '/packages/${{ github.run_id }}-${{ github.run_attempt }}'

    environment:
      name: ${{ inputs.environment }}

    steps:

      - if: ${{ !(inputs.nuget-feed-server == 'NuGet' || inputs.nuget-feed-server == 'AzureArtifacts') }}
        name: 'Invalid NuGet feed server type'
        shell: bash
        run: |
          echo 'Invalid NuGet feed server type ${{ inputs.nuget-feed-server }}. Allowed values are 'NuGet' or 'AzureArtifacts'.'
          exit 1

      - name: 'Setup .NET ${{ inputs.dotnet-sdk-version }}'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-sdk-version }}

      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.artifact-run-id }}
          name: ${{ inputs.artifact-name }}
          path: ${{ runner.temp }}/${{ env.working-directory }}

      - if: ${{ inputs.nuget-feed-server == 'NuGet' }}
        name: 'Publish package to NuGet'
        shell: bash
        run: |
          dotnet nuget push **/*.nupkg --source ${{ vars.NUGET_PACKAGE_FEED_URL }} --api-key ${{ secrets.NUGET_PACKAGE_FEED_API_KEY }}
        working-directory: ${{ runner.temp }}/${{ env.working-directory }}

      - if: ${{ inputs.nuget-feed-server == 'AzureArtifacts' }}
        name: 'Publish package to Azure Artifacts'
        shell: bash
        run: |
          dotnet nuget add source ${{ vars.NUGET_PACKAGE_FEED_URL }} --name nuget-feed --username username --password ${{ secrets.NUGET_PACKAGE_FEED_API_KEY }} --store-password-in-clear-text
          dotnet nuget push **/*.nupkg --source nuget-feed --api-key ${{ secrets.NUGET_PACKAGE_FEED_API_KEY }} --skip-duplicate
        working-directory: ${{ runner.temp }}/${{ env.working-directory }}