name: 'Generate & Publish Documentation'

on:
  workflow_run:
    workflows: ['build']

    types:
      - completed

permissions:
  actions: read
  pages: write
  id-token: write

concurrency: 
  group: publish-docs-${{ github.head_ref || github.ref }}      
  cancel-in-progress: false

jobs:
  global-variables:
    name: 'Global variables'
    runs-on: ubuntu-latest

    outputs:
      github-run-number: ${{ github.run_number }}

    steps:
      - name: 'Global variables'
        id: github
        run: |
          echo "github-run-number:${{ github.run_number }}"

  versioning:
    name: Versioning with GitVersion
    needs: [global-variables]
    uses: ./.github/workflows/determine-version.yml
    with:
      config-file-path: './.gitversion/version.yml'
      run-number: ${{ needs.global-variables.outputs.github-run-number }}

  generate-docs:
    name: 'Generate documentation'
    needs: [global-variables, versioning]
    runs-on: ubuntu-latest
    env:
      friendly-version: ${{ needs.versioning.outputs.friendly-version }}
    steps:
      - name: 'Checkout ${{ github.head_ref || github.ref }}'
        uses: actions/checkout@v4

      - name: 'Generate documentation'
        uses: ./.github/actions/docfx-build
        with:
          artifact-name: 'documentation'
          docfx-json-manifest: './api-reference/api-reference.json'
          output-directory: './api-reference/_docs'

      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './api-reference/_docs'

  publish-docs:
    name: 'Publish documentation'
    needs: [global-variables, versioning, generate-docs]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4